In [1]:
import numpy as np

In [2]:
np.array([10,20,30,40,50])

array([10, 20, 30, 40, 50])

In [3]:
type(np.array([10,20,30,40,50]))

numpy.ndarray

In [4]:
 new_array = np.array([10,20,5.8,37.6,53,67.1], dtype="float32")

In [5]:
new_array

array([10. , 20. ,  5.8, 37.6, 53. , 67.1], dtype=float32)

In [6]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
np.full((3,3),5)      # 3*3'lük 5 değerlerinden oluşan matris

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
np.arange(10,20,2)    #10-20 arasında 2 arttırarak yazdırır.

array([10, 12, 14, 16, 18])

In [10]:
np.linspace(10,20,5)  #10-20 arasında 5 tane sayı yazdırır.

array([10. , 12.5, 15. , 17.5, 20. ])

In [11]:
np.random.normal(1,2,(4,5))  # ortalaması 1, standart sapması 2 olan 4*5'lik matris

array([[-1.9524076 , -0.77447245, -3.23177501,  2.23557505,  6.21509108],
       [ 0.58925602,  2.38354647,  0.23165959,  5.50778897,  1.67934949],
       [ 2.59458839, -0.30342612, -0.49011039, -2.63782804,  1.32961064],
       [ 0.56180287,  1.59025135,  3.47081545,  4.77978444, -0.7343232 ]])

In [12]:
np.random.randint(2,10,(4,6)) #değerleri 2-10 olan 4*6'lık matris

array([[6, 7, 9, 5, 5, 3],
       [8, 3, 2, 2, 5, 8],
       [5, 7, 8, 7, 6, 4],
       [7, 4, 9, 2, 7, 8]])

# Özellikleri

In [13]:
yeni = np.random.randint(15, size=8)

In [14]:
yeni

array([ 5,  0, 14,  5,  5,  4, 13,  0])

In [15]:
baska_degisken = np.random.randint(5, size = (3,3,3))

In [16]:
baska_degisken

array([[[2, 1, 0],
        [2, 4, 4],
        [0, 3, 2]],

       [[3, 2, 4],
        [1, 3, 2],
        [2, 0, 1]],

       [[2, 0, 1],
        [2, 3, 0],
        [2, 1, 1]]])

In [17]:
array = np.random.randint(1,10,(3,3))  #rastgele dağılımlı tamsayılardan oluşan array

In [22]:
array.ndim

2

In [23]:
array.shape

(3, 3)

In [24]:
array.size

9

In [25]:
array.dtype

dtype('int32')

In [26]:
baska_degisken.shape

(3, 3, 3)

In [27]:
baska_degisken.ndim

3

# Boyut Özellikleri

In [28]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
a = np.random.randint(16, size=(5,5))

In [31]:
a

array([[14,  2, 14,  3, 14],
       [ 7,  1,  7, 15, 10],
       [13,  5,  7,  4, 10],
       [ 5,  1,  4,  8,  1],
       [12, 11,  8, 12,  6]])

In [32]:
np.arange(1,16).reshape((3,5))  # matrise çevirdik.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
onemli_1 = np.array([2,3,4]) # vektörü matrise çevirme?

In [34]:
onemli_2 = onemli_1.reshape((1,3)) # yeniden boyutlandırma ile matrise dönüştü.

In [35]:
onemli_1.shape  # vektör

(3,)

In [36]:
onemli_2.shape  # matris

(1, 3)

In [37]:
onemli_1.ndim

1

In [38]:
onemli_2.ndim

2

In [39]:
onemli_1.size

3

In [40]:
onemli_2.size

3

In [41]:
onemli_1[np.newaxis, :]  # tek boyutlu değişken 2 boyutluya dönüştü.

array([[2, 3, 4]])

In [42]:
onemli_1 # tek boyutlu değişken

array([2, 3, 4])

In [43]:
onemli_1[:, np.newaxis]  

array([[2],
       [3],
       [4]])

# Array Birleştirme

In [50]:
import numpy as np

In [51]:
x = np.array([1,3,5])
y = np.array([2,4,6])

In [52]:
x

array([1, 3, 5])

In [53]:
y

array([2, 4, 6])

In [54]:
np.concatenate([x,y])   # 2 array birleştirildi.

array([1, 3, 5, 2, 4, 6])

In [55]:
z = np.array([7,8,9])

In [56]:
np.concatenate([x,y,z])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [57]:
a = np.array([[1,2,3],[4,5,6]])

In [58]:
np.concatenate([a,a])  # satır bazında birleştirme yaptı.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([a,a,a], axis =1)  # sütunları birleştirdi.

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [60]:
a = np.array([[1,2,3],[4,5,6]])  # Boyutları farklı iki diziyi birleştirme
b = np.array([7,8,9])

In [61]:
a.ndim  

2

In [62]:
b.ndim

1

In [63]:
np.vstack([a,b])   #satır bazında birleştirme yaptık.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
c = np.array([[12],[13]])

In [65]:
c.shape

(2, 1)

In [66]:
a.shape

(2, 3)

#  a ve c matrislerinin satır sayıları aynı olduğu için birleştirme yapılabilir.

In [67]:
np.hstack([a,c])   #sütun olarak ekledi

array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 13]])

# Array ayırma işlemleri

In [68]:
import numpy as np

In [69]:
 yeni = [1,2,3,6,9,45,61,28,79]

In [70]:
yeni

[1, 2, 3, 6, 9, 45, 61, 28, 79]

In [71]:
yeni1, yeni2, yeni3 = np.split(yeni,[2,6])

In [72]:
yeni1

array([1, 2])

In [73]:
yeni3

array([61, 28, 79])

In [74]:
x = np.arange(16).reshape((4,4))

In [75]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
x1,x2 = np.vsplit(x,[2])

In [77]:
x1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [78]:
x2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
x3, x4 = np.hsplit(x, [2])

In [80]:
x3

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [81]:
x4

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sıralama İşlemleri

In [82]:
import numpy as np

In [83]:
x = np.array([1,6,5,2,9])

In [84]:
x

array([1, 6, 5, 2, 9])

In [85]:
np.sort(x)  #sıralama yaptık.

array([1, 2, 5, 6, 9])

In [86]:
x

array([1, 6, 5, 2, 9])

In [90]:
x.sort()  #kalıcı kaydeder.

In [91]:
x

array([1, 2, 5, 6, 9])

In [92]:
x = np.array([1,6,5,2,9])

In [93]:
y = np.argsort(x)   #array sırası indise göre değişiyor.

In [95]:
y                   # x'te 3.eleman(2 sayısı) y dizisinde 1 .eleman olarak atanır.

array([0, 3, 2, 1, 4], dtype=int64)

In [96]:
x[y]

array([1, 2, 5, 6, 9])

In [97]:
x

array([1, 6, 5, 2, 9])

# Index İşlemleri

In [98]:
import numpy as np

In [101]:
x = np.random.randint(15, size=15 )

In [102]:
x

array([ 3,  0,  4,  3,  4, 11,  4,  1,  8,  7,  3,  5,  6,  5, 13])

In [104]:
x[-1]  #son eleman

13

In [106]:
x[-2] 

5

In [107]:
x[-2] = 10   #indisin değerini değiştirdik.

In [108]:
x

array([ 3,  0,  4,  3,  4, 11,  4,  1,  8,  7,  3,  5,  6, 10, 13])

In [109]:
y = np.random.randint(15, size = (3,4))

In [110]:
y

array([[12,  5,  0,  3],
       [ 4,  8,  3,  5],
       [12, 13, 14, 11]])

In [111]:
y[0][0]

12

In [114]:
y[2,2]

14

In [117]:
y[2,2] = 29 #değer değiştirme

In [118]:
y

array([[12,  5,  0,  3],
       [ 4,  8,  3,  5],
       [12, 13, 29, 11]])

In [119]:
y[2,3] = 6.3  

In [120]:
y

array([[12,  5,  0,  3],
       [ 4,  8,  3,  5],
       [12, 13, 29,  6]])