In [2]:
import numpy as np

# numpy array

In [2]:
myList = [20,30,50]

In [3]:
np.array(myList)

array([20, 30, 50])

In [4]:
type(np.array(myList))

numpy.ndarray

In [5]:
matrixList = [[10,20,30],[20,60,50],[30,60,0]]

In [6]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 60, 50],
       [30, 60,  0]])

In [7]:
matrixList[2][1]

60

# arange

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,22,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [11]:
myList = list(range(0,12))

In [12]:
myList

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [14]:
myList[::-2] #sondan 2 azaltarak yazar

[11, 9, 7, 5, 3, 1]

In [15]:
np.zeros(5) #5 sıfırdan oluşan array

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5)) # 5*5'lik sıfırlardan oluşan matris.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.ones((3,3))  # 1'lerden oluşan matris

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# linspace

In [18]:
np.linspace(10,20,9)   #10-20 arasında 9 sayı yazdı.

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

# eye

In [19]:
np.eye(5)  # köşegen matrisi oluşturur

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.randn(4)  # rastgele 4 değer alma

array([-1.33218686,  0.55945684,  0.5188032 ,  0.22037892])

In [22]:
np.random.randn(2,2)

array([[ 1.8976502 ,  1.42811262],
       [ 0.12627047, -0.62194972]])

In [23]:
np.random.randint(1,10,5)

array([4, 2, 8, 9, 3])

In [24]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [25]:
np.random.randint(1,10,6)

array([9, 4, 8, 7, 2, 3])

In [26]:
benimNumpyDizim = np.arange(10)

In [24]:
benimNumpyDizim

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
benimRandDizim = np.random.randint(0,100,20)

In [26]:
benimRandDizim

array([91, 92, 22, 46, 26, 31, 79, 16, 37,  4, 46, 98, 39, 33, 75, 75, 82,
       92, 92, 45])

# numpy dizi örnekleri

In [32]:
benimNumpyDizim.reshape(2,5)  # 10 eleman vardı (5,2) olabiliir

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
benimRandDizim.max()

98

In [34]:
benimRandDizim.min()

4

In [35]:
benimRandDizim.argmin()  # kaçıncı indeks min değer?

9

In [36]:
benimNumpyDizim.shape

(10,)

In [37]:
benimNumpyDizim

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
reshape = benimNumpyDizim.reshape(2,5)

In [42]:
reshape.shape

(2, 5)

In [4]:
import numpy as np

In [44]:
myDizi = np.arange(0,15)

In [45]:
myDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
myDizi[5]

5

In [49]:
myDizi[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
myDizi[::-2]  #ters yönden ikişer gider 

array([14, 12, 10,  8,  6,  4,  2,  0])

In [55]:
myDizi[3:8] = -5  # 3-8 arasını -5 yaptık

In [56]:
myDizi       

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [57]:
newDizi = np.arange(0,23)

In [58]:
newDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [62]:
slicingDizisi = newDizi[3:8]

In [63]:
slicingDizisi

array([3, 4, 5, 6, 7])

In [64]:
newDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [68]:
slicingDizisi [:] = 300 #dizinin tüm elemanlarını 300 yaptık

In [69]:
slicingDizisi 

array([300, 300, 300, 300, 300])

In [70]:
newDizi # 3-8 indis de değişti

array([  0,   1,   2, 300, 300, 300, 300, 300,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22])

In [71]:
ornekDizi = np.arange(20)

In [72]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
kopyaornekDizi = ornekDizi.copy()

In [74]:
kopyaornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
SlicingkopyaornekDizi = kopyaornekDizi[2:6]

In [77]:
SlicingkopyaornekDizi[:] = 300

In [78]:
SlicingkopyaornekDizi

array([300, 300, 300, 300])

In [79]:
kopyaornekDizi

array([  0,   1, 300, 300, 300, 300,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [80]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# matrix

In [81]:
myList = [[10,0,30],[20,60,80],[90,45,71 ]]

In [82]:
ornekMatrixDizisi = np.array(myList)

In [83]:
ornekMatrixDizisi

array([[10,  0, 30],
       [20, 60, 80],
       [90, 45, 71]])

In [99]:
#ornekMatrixDizisi.transpose()[1]        # transpoz kullanmadan[ :,1]
ornekMatrixDizisi[:,1]

array([ 0, 60, 45])

In [90]:
ornekMatrixDizisi[1][2]

80

In [91]:
ornekMatrixDizisi[1,2]

80

In [94]:
ornekMatrixDizisi[1:,2]   # 2.sütunda 1ve sonrasını alıyor

array([30, 80, 71])

In [100]:
newList =[[12,3,65,12,48],[25,36,95,15,84],[20,62,59,65,24]]

In [101]:
yeniMatrix = np.array(newList)

In [102]:
newList

[[12, 3, 65, 12, 48], [25, 36, 95, 15, 84], [20, 62, 59, 65, 24]]

In [103]:
yeniMatrix

array([[12,  3, 65, 12, 48],
       [25, 36, 95, 15, 84],
       [20, 62, 59, 65, 24]])

In [105]:
yeniMatrix[1,3]

15

In [108]:
yeniMatrix[[2,0,1]]  # önce 2.satır sonra 0 sonra 1'i yazdırır.

array([[20, 62, 59, 65, 24],
       [12,  3, 65, 12, 48],
       [25, 36, 95, 15, 84]])

In [28]:
np.array(myList)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

# operasyonler

In [31]:
yeniDizi = np.random.randint(5,20,10)

In [32]:
yeniDizi

array([18, 13, 11,  8,  7, 11, 10, 10, 10, 17])

In [39]:
sonucDizisi = yeniDizi > 10

In [40]:
sonucDizisi

array([ True,  True,  True, False, False,  True, False, False, False,
        True])

In [41]:
yeniDizi[sonucDizisi]  # 10 dan büyük olan = true'ları yazdırdı

array([18, 13, 11, 11, 17])

In [44]:
yeniDizi[yeniDizi > 10]  # direkt 10 dan büyük olanları yazdırır

array([18, 13, 11, 11, 17])

In [54]:
sonDizi = np.arange(0,20)

In [55]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
sonDizi **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [57]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [58]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
 sonDizi ** (1/2)   #karekök

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [60]:
np.square(sonDizi)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [61]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [62]:
np.max(sonDizi)

19

In [63]:
np.min(sonucDizisi)

False

In [64]:
np.argmax(sonDizi)

19

In [68]:
sonucDizisi.argpartition(2)

array([3, 4, 6, 0, 1, 5, 2, 7, 8, 9], dtype=int64)

In [70]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
np.count_nonzero(sonDizi == 2) #nump için count kullanımı

1

In [5]:
import numpy as np
myList = [20,30,50]
np.array(myList)


array([20, 30, 50])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(10,20,9)   

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])